global:
  scrape_interval: 5s

scrape_configs:
  - job_name: prometheus
    honor_labels: true
    static_configs:
      - targets: [ "localhost:9090" ]
  - job_name: 'spring_micrometer'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['your_host_ip:8080']